spring:
  mail:
    protocol: smtp
    username: ${feast.email}
    password: ${feast.password}
  datasource:
    url: jdbc:postgresql://localhost:5432/feast
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

feast.base.url: https://feast.com
edamam.base.url: https://api.edamam.com/
edamam.api.id: 7b6bc7d2
edamam.api.app_keys: 86969d07c7c1ae899323ad85b6eca8ef