spring:
  mail:
    protocol: smtp
    username: ${feast_emailAddress}
    password: ${feast_password}
  datasource:
    url: jdbc:postgresql://localhost:5432/feast
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

feast_base_url: https://feast.com
edamam_base_url: https://api.edamam.com/api/recipes/v2
edamam_api_id: ${edamam_api_id}
edamam_api_app_keys: ${edamam_api_app_keys}
secret_key: ${secret_key}